import type { Rule } from './analytics.ts';
export const ruleTemplates: { name: string; rule: Omit<Rule, 'id'> }[] = [
  {
    name: 'High Burden',
    rule: {
      metric: 'incidence',
      operator: '>',
      value: 300,
      secondary: { metric: 'change', operator: '>', value: 20 },
      join: 'AND',
      severity: 'HIGH',
      category: 'Burden',
      description:
        'Incidence exceeds 300 per 1,000 and annual observed cases increase more than 20%.',
      priority: 'HIGH',
      persistence: 1,
      suppress: true,
      enabled: true,
    },
  },
  {
    name: 'Rapid Increase',
    rule: {
      metric: 'cases',
      operator: 'increased by',
      value: 20,
      severity: 'HIGH',
      category: 'Trend',
      description: 'Observed cases increase by at least 20% against the previous adjacent year.',
      priority: 'HIGH',
      persistence: 1,
      suppress: true,
      enabled: true,
    },
  },
  {
    name: 'Climate Anomaly',
    rule: {
      metric: 'rainfall_anomaly',
      operator: 'outside range',
      value: -2,
      upper: 2,
      secondary: { metric: 'temperature_anomaly', operator: 'outside range', value: -2, upper: 2 },
      join: 'OR',
      severity: 'WATCH',
      category: 'Climate',
      description: 'Rainfall or temperature lies outside ±2 historical sample standard deviations.',
      priority: 'NORMAL',
      persistence: 1,
      suppress: true,
      enabled: true,
    },
  },
  {
    name: 'Model Deviation',
    rule: {
      metric: 'prediction_increase',
      operator: '>',
      value: 30,
      severity: 'WATCH',
      category: 'Model',
      description:
        'Selected-model prediction exceeds the mean of up to three earlier observed periods by more than 30%.',
      priority: 'NORMAL',
      persistence: 1,
      suppress: true,
      enabled: true,
    },
  },
  {
    name: 'Data Gap',
    rule: {
      metric: 'data_completeness',
      operator: '<',
      value: 80,
      severity: 'INFO',
      category: 'Data Quality',
      description: 'Fewer than 80% of six analytical input fields are available.',
      priority: 'NORMAL',
      persistence: 1,
      suppress: true,
      enabled: true,
    },
  },
  {
    name: 'Persistent High Risk',
    rule: {
      metric: 'risk_level',
      operator: '>=',
      value: 2,
      severity: 'HIGH',
      category: 'Risk',
      description:
        'Incidence-based risk remains HIGH or VERY HIGH for three adjacent annual periods.',
      priority: 'HIGH',
      persistence: 3,
      suppress: true,
      enabled: true,
    },
  },
];
